apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nasa-apod
  labels:
    app: {{ .Release.Name }}-nasa-apod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nasa-apod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nasa-apod
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:   
            - name: PORT   
              value: {{ .Values.service.targetPort | quote }}   
            - name: PYTHONUNBUFFERED   
              value: "1"   
            - name: NASA_API_KEY   
              value: {{ .Values.nasaApiKey | quote }}   
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
