apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nasa-apod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: nasa-apod.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-nasa-apod
                port:
                  number: {{ .Values.service.port }}
